export const GSETS: Record<string, string[]> = {
  "K·▪":      " .·:∶k×Kﬀ▪◼█".split(""),
  "Classic":  " .,:;i1tfLCG08@".split(""),
  "Dense":    " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$".split(""),
  "Blocks":   " .:-=+░▒▓█".split(""),
  "Dots":     " ·∙•●⬤".split(""),
  "Shade":    " ░▒▓█".split(""),
  "Binary":   " 01".split(""),
  "Morse":    " ·−■".split(""),
  "Geo":      " ·˙∘○◎◉●".split(""),
  "Squares":  " ▫▪◻◼⬜⬛".split(""),
  "Triangles":" ᐧ◁△▽▷◀▲▼▶◆".split(""),
  "Diamond":  " ◇◈◆❖".split(""),
  "Stars":    " ✦✧⋆★✪✫❋✹".split(""),
  "Sparkle":  " ˙·✧✦⊹❋✺✹✸".split(""),
  "Matrix":   " .ﾊﾐﾋｰｳｼﾅﾓﾆｻﾜﾂｵﾘｱﾎﾃﾏｹﾒｴｶｷﾑﾕﾗｾﾈ012345789日".split(""),
  "Braille":  [" ","⠁","⠂","⠄","⠌","⠒","⠔","⠢","⠣","⠥","⠶","⠷","⠿","⣿"],
  "Hangul":   " ㅡㅣㄱㄴㅂㅁㅎㅊㅍ뫏".split(""),
  "Runes":    " ·ᚢᚦᚱᚻᛉᛊᛋᛗᛞᛟ".split(""),
  "Arabic":   " ·ـﻊﺣﻐﻤﺿﺼﻈﻅ".split(""),
  "Greek":    " ·.:ιτπφψΩΞΨ".split(""),
  "Math":     " ·+÷×∑∫∬∭∰".split(""),
  "Currency": " ·¢€£¥₿₹₩$".split(""),
  "Music":    " ♩♪♫♬𝄞".split(""),
  "Zodiac":   " ☽☆♃♄♅♆♇⊕☉".split(""),
  "Circuit":  " ·˙╌╎┊┋╬╠╣".split(""),
  "Pipes":    " ·─│┌┐└┘├┤┬┴┼╋".split(""),
  "Hacker":   " .01{}[]<>/\\|#@".split(""),
  "Digits":   " 1234567890".split(""),
  "Rain":     " ᐧ.·:│║ⅼ‖▌".split(""),
  "Waves":    " ~≈∿⌇⌇∿≋≋".split(""),
  "Cross":    " ·+×✕✖✚✜✛❖".split(""),
  "Arrows":   " →↗↑↖←↙↓↘⬡⬢".split(""),
  "Chaos":    " ░▒▓┼╬◆●★▲■".split(""),
  "Emoji":    " 🌑🌒🌓🌔🌕".split(""),
  "Skull":    " ·.░☠▒▓█".split(""),
};

export type GlyphSetName = keyof typeof GSETS;
